### ISSUE TITLE
Alphabetical ordering in the authlist.py script

### ISSUE THREAD

**Issue by joezuntz** [kadrlica/destools#1]
Hi,

The authlist.py script does not correctly alphabetize accented characters. e.g. S\'{a}nchez appears after Swanson.

Thanks for you awesome script!
Joe

**Comment by kadrlica** [comment]
This is strange since the sorting is done on the "Lastname" field (which shouldn't have any special latex characters). Can you post/email me a copy of your author list csv file and the command that you are using to call authlist.py?

**Comment by joezuntz** [comment]
Apologies, I must have been doing something stupid here.  Only one remaining issue - Michael Busha doesn't have an affiliation and that throws out the numbering scheme - I get a blank but numbered affiliation.

**Comment by kadrlica** [comment]
That is a "feature" of the PubDB system. Collaborators at non-DES institutions are given blank affiliations. You will need to insert Michael's affiliation into your csv file. (It would also be possible to hack your local version of authlist.py to add the affiliation, there is an example where I was hacking the Munich affiliations [here](https://github.com/kadrlica/destools/blob/master/python/authlist.py#L193-L197))

**Comment by joezuntz** [comment]
Thanks - I've done that.
